name: Build & Publish Electron App (Windows + macOS)

on:
  push:
    tags:
      - 'v*'  # 例如 v0.8.2

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 修复 latest.yml 的 sha512
        run: npm run fix:sha512

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap

  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build macOS DMG
  #       run: npm run dist:mac
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
